"""create_m02_tables

Revision ID: 1df83d9054f8
Revises: f46b7c5f45e5
Create Date: 2026-07-20 05:30:27.346494
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '1df83d9054f8'
down_revision: str | None = 'f46b7c5f45e5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('code_repositories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('repository_type', sa.String(length=50), nullable=False),
    sa.Column('provider_type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('remote_url', sa.String(length=1024), nullable=False),
    sa.Column('auth_type', sa.String(length=50), nullable=False),
    sa.Column('credential_ref', sa.String(length=255), nullable=True),
    sa.Column('main_branch', sa.String(length=100), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('sync_status', sa.String(length=50), nullable=False),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_synced_head_sha', sa.String(length=40), nullable=True),
    sa.Column('last_error_code', sa.String(length=100), nullable=True),
    sa.Column('last_error_message', sa.Text(), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_code_repositories_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_code_repositories'))
    )
    op.create_index(op.f('ix_code_repositories_project_id'), 'code_repositories', ['project_id'], unique=True)
    op.create_table('requirements',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('requirement_no', sa.String(length=100), nullable=False),
    sa.Column('requirement_no_normalized', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('acceptance_criteria', sa.Text(), nullable=True),
    sa.Column('priority', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=True),
    sa.Column('tags_json', sa.JSON(), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_requirements_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_requirements_owner_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_requirements_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_requirements_updated_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_requirements')),
    sa.UniqueConstraint('project_id', 'requirement_no_normalized', name='uq_requirements_project_no')
    )
    op.create_index(op.f('ix_requirements_project_id'), 'requirements', ['project_id'], unique=False)
    op.create_table('versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('key_normalized', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('planned_start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('planned_end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('previous_status', sa.String(length=50), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_versions_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_versions_owner_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_versions_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_versions_updated_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_versions')),
    sa.UniqueConstraint('project_id', 'key_normalized', name='uq_versions_project_key')
    )
    op.create_index(op.f('ix_versions_project_id'), 'versions', ['project_id'], unique=False)
    op.create_table('git_commits',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('repository_id', sa.Uuid(), nullable=False),
    sa.Column('sha', sa.String(length=40), nullable=False),
    sa.Column('author_name', sa.String(length=100), nullable=False),
    sa.Column('author_email', sa.String(length=255), nullable=False),
    sa.Column('committer_name', sa.String(length=100), nullable=False),
    sa.Column('committer_email', sa.String(length=255), nullable=False),
    sa.Column('authored_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('committed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('parent_shas_json', sa.JSON(), nullable=True),
    sa.Column('is_merge', sa.Boolean(), nullable=False),
    sa.Column('is_reachable_from_main', sa.Boolean(), nullable=False),
    sa.Column('files_changed', sa.Integer(), nullable=False),
    sa.Column('additions', sa.Integer(), nullable=False),
    sa.Column('deletions', sa.Integer(), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['code_repositories.id'], name=op.f('fk_git_commits_repository_id_code_repositories'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_git_commits')),
    sa.UniqueConstraint('repository_id', 'sha', name='uq_git_commits_repo_sha')
    )
    op.create_index(op.f('ix_git_commits_repository_id'), 'git_commits', ['repository_id'], unique=False)
    op.create_table('repository_sync_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('repository_id', sa.Uuid(), nullable=False),
    sa.Column('job_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('requested_by', sa.Uuid(), nullable=True),
    sa.Column('requirement_id', sa.Uuid(), nullable=True),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lease_owner', sa.String(length=100), nullable=True),
    sa.Column('lease_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('metrics_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_repository_sync_jobs_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repository_id'], ['code_repositories.id'], name=op.f('fk_repository_sync_jobs_repository_id_code_repositories'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], name=op.f('fk_repository_sync_jobs_requested_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], name=op.f('fk_repository_sync_jobs_requirement_id_requirements'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_repository_sync_jobs'))
    )
    op.create_index(op.f('ix_repository_sync_jobs_project_id'), 'repository_sync_jobs', ['project_id'], unique=False)
    op.create_index(op.f('ix_repository_sync_jobs_repository_id'), 'repository_sync_jobs', ['repository_id'], unique=False)
    op.create_table('requirement_attachments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('requirement_id', sa.Uuid(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('storage_key', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('referenced_count', sa.Integer(), nullable=False),
    sa.Column('uploaded_by', sa.Uuid(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('archived_by', sa.Uuid(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['archived_by'], ['users.id'], name=op.f('fk_requirement_attachments_archived_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_requirement_attachments_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], name=op.f('fk_requirement_attachments_requirement_id_requirements'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name=op.f('fk_requirement_attachments_uploaded_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_requirement_attachments'))
    )
    op.create_index(op.f('ix_requirement_attachments_project_id'), 'requirement_attachments', ['project_id'], unique=False)
    op.create_index(op.f('ix_requirement_attachments_requirement_id'), 'requirement_attachments', ['requirement_id'], unique=False)
    op.create_table('version_requirements',
    sa.Column('version_id', sa.Uuid(), nullable=False),
    sa.Column('requirement_id', sa.Uuid(), nullable=False),
    sa.Column('linked_by', sa.Uuid(), nullable=True),
    sa.Column('linked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('removed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['linked_by'], ['users.id'], name=op.f('fk_version_requirements_linked_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], name=op.f('fk_version_requirements_requirement_id_requirements'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['version_id'], ['versions.id'], name=op.f('fk_version_requirements_version_id_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('version_id', 'requirement_id', name=op.f('pk_version_requirements'))
    )
    op.create_table('git_commit_files',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('commit_id', sa.Uuid(), nullable=False),
    sa.Column('old_path', sa.Text(), nullable=True),
    sa.Column('new_path', sa.Text(), nullable=False),
    sa.Column('change_type', sa.String(length=50), nullable=False),
    sa.Column('is_binary', sa.Boolean(), nullable=False),
    sa.Column('additions', sa.Integer(), nullable=False),
    sa.Column('deletions', sa.Integer(), nullable=False),
    sa.Column('patch_storage_key', sa.String(length=255), nullable=True),
    sa.Column('patch_size_bytes', sa.Integer(), nullable=False),
    sa.Column('patch_truncated', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['commit_id'], ['git_commits.id'], name=op.f('fk_git_commit_files_commit_id_git_commits'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_git_commit_files'))
    )
    op.create_index(op.f('ix_git_commit_files_commit_id'), 'git_commit_files', ['commit_id'], unique=False)
    op.create_table('requirement_commit_links',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('requirement_id', sa.Uuid(), nullable=False),
    sa.Column('commit_id', sa.Uuid(), nullable=False),
    sa.Column('matched_requirement_no', sa.String(length=100), nullable=False),
    sa.Column('match_revision', sa.Integer(), nullable=False),
    sa.Column('match_method', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('staled_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['commit_id'], ['git_commits.id'], name=op.f('fk_requirement_commit_links_commit_id_git_commits'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_requirement_commit_links_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], name=op.f('fk_requirement_commit_links_requirement_id_requirements'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_requirement_commit_links')),
    sa.UniqueConstraint('requirement_id', 'commit_id', 'match_revision', name='uq_req_commit_link')
    )
    op.create_index(op.f('ix_requirement_commit_links_commit_id'), 'requirement_commit_links', ['commit_id'], unique=False)
    op.create_index(op.f('ix_requirement_commit_links_project_id'), 'requirement_commit_links', ['project_id'], unique=False)
    op.create_index(op.f('ix_requirement_commit_links_requirement_id'), 'requirement_commit_links', ['requirement_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_requirement_commit_links_requirement_id'), table_name='requirement_commit_links')
    op.drop_index(op.f('ix_requirement_commit_links_project_id'), table_name='requirement_commit_links')
    op.drop_index(op.f('ix_requirement_commit_links_commit_id'), table_name='requirement_commit_links')
    op.drop_table('requirement_commit_links')
    op.drop_index(op.f('ix_git_commit_files_commit_id'), table_name='git_commit_files')
    op.drop_table('git_commit_files')
    op.drop_table('version_requirements')
    op.drop_index(op.f('ix_requirement_attachments_requirement_id'), table_name='requirement_attachments')
    op.drop_index(op.f('ix_requirement_attachments_project_id'), table_name='requirement_attachments')
    op.drop_table('requirement_attachments')
    op.drop_index(op.f('ix_repository_sync_jobs_repository_id'), table_name='repository_sync_jobs')
    op.drop_index(op.f('ix_repository_sync_jobs_project_id'), table_name='repository_sync_jobs')
    op.drop_table('repository_sync_jobs')
    op.drop_index(op.f('ix_git_commits_repository_id'), table_name='git_commits')
    op.drop_table('git_commits')
    op.drop_index(op.f('ix_versions_project_id'), table_name='versions')
    op.drop_table('versions')
    op.drop_index(op.f('ix_requirements_project_id'), table_name='requirements')
    op.drop_table('requirements')
    op.drop_index(op.f('ix_code_repositories_project_id'), table_name='code_repositories')
    op.drop_table('code_repositories')
    # ### end Alembic commands ###
