"""add_p2_runtime_tables_and_fields

Revision ID: 30afeeaaf04a
Revises: 3265b622f4b4
Create Date: 2026-07-22 08:33:43.810402
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "30afeeaaf04a"
down_revision: str | None = "3265b622f4b4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ai_human_gate_actions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("step_execution_id", sa.UUID(), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("action", sa.String(length=50), nullable=False),
        sa.Column("decision_snapshot", sa.JSON(), nullable=False),
        sa.Column("decision_hash", sa.String(length=64), nullable=False),
        sa.Column("submitted_by", sa.UUID(), nullable=True),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["ai_capability_runs.id"],
            name="fk_ai_human_gate_actions_run_id",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["step_execution_id"],
            ["ai_step_executions.id"],
            name="fk_ai_human_gate_actions_step_exec_id",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["submitted_by"],
            ["users.id"],
            name="fk_ai_human_gate_actions_submitted_by_users",
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_human_gate_actions")),
        sa.UniqueConstraint(
            "step_execution_id", "attempt", name="uq_ai_human_gate_actions_step_attempt"
        ),
    )
    op.create_table(
        "ai_run_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("step_execution_id", sa.UUID(), nullable=True),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("trace_id", sa.String(length=100), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "sequence > 0", name=op.f("ck_ai_run_events_ck_ai_run_events_sequence_positive")
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["ai_capability_runs.id"],
            name="fk_ai_run_events_run_id_ai_capability_runs",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["step_execution_id"],
            ["ai_step_executions.id"],
            name="fk_ai_run_events_step_exec_id_ai_step_executions",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_run_events")),
        sa.UniqueConstraint("run_id", "sequence", name="uq_ai_run_events_run_sequence"),
    )
    op.create_table(
        "ai_step_output_snapshots",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("step_execution_id", sa.UUID(), nullable=False),
        sa.Column("output_snapshot", sa.JSON(), nullable=False),
        sa.Column("output_hash", sa.String(length=64), nullable=False),
        sa.Column("output_schema_snapshot", sa.JSON(), nullable=True),
        sa.Column("validator_results", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["step_execution_id"],
            ["ai_step_executions.id"],
            name="fk_ai_step_output_snapshots_step_exec_id",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_step_output_snapshots")),
        sa.UniqueConstraint(
            "step_execution_id", name="uq_ai_step_output_snapshots_step_execution_id"
        ),
    )
    op.add_column("ai_capability_runs", sa.Column("run_mode", sa.String(length=20), nullable=False))
    op.add_column("ai_capability_runs", sa.Column("execution_snapshot", sa.JSON(), nullable=False))
    op.add_column(
        "ai_capability_runs",
        sa.Column("execution_snapshot_hash", sa.String(length=64), nullable=True),
    )
    op.add_column(
        "ai_capability_runs", sa.Column("idempotency_key", sa.String(length=100), nullable=True)
    )
    op.add_column(
        "ai_capability_runs", sa.Column("request_fingerprint", sa.String(length=64), nullable=True)
    )
    op.add_column(
        "ai_capability_runs", sa.Column("next_event_sequence", sa.Integer(), nullable=False)
    )
    op.add_column(
        "ai_capability_runs",
        sa.Column("cancel_requested_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column("ai_capability_runs", sa.Column("cancel_requested_by", sa.UUID(), nullable=True))
    op.add_column(
        "ai_capability_runs", sa.Column("final_output_snapshot_id", sa.UUID(), nullable=True)
    )
    op.add_column(
        "ai_capability_runs", sa.Column("deadline_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column("ai_capability_runs", sa.Column("usage_snapshot", sa.JSON(), nullable=True))
    op.add_column(
        "ai_capability_runs", sa.Column("error_code", sa.String(length=100), nullable=True)
    )
    op.add_column("ai_capability_runs", sa.Column("error_summary", sa.Text(), nullable=True))
    op.create_unique_constraint(
        "uq_ai_capability_runs_proj_init_idempotency",
        "ai_capability_runs",
        ["project_id", "initiator_id", "idempotency_key"],
    )
    op.create_foreign_key(
        "fk_ai_capability_runs_cancel_requested_by_users",
        "ai_capability_runs",
        "users",
        ["cancel_requested_by"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column(
        "ai_step_executions", sa.Column("node_type", sa.String(length=50), nullable=False)
    )
    op.add_column(
        "ai_step_executions", sa.Column("node_name", sa.String(length=100), nullable=True)
    )
    op.add_column("ai_step_executions", sa.Column("input_snapshot", sa.JSON(), nullable=True))
    op.add_column("ai_step_executions", sa.Column("input_summary", sa.JSON(), nullable=True))
    op.add_column(
        "ai_step_executions", sa.Column("available_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "ai_step_executions", sa.Column("claim_owner", sa.String(length=100), nullable=True)
    )
    op.add_column(
        "ai_step_executions",
        sa.Column("claim_expires_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column("ai_step_executions", sa.Column("claim_version", sa.Integer(), nullable=False))
    op.add_column("ai_step_executions", sa.Column("retry_of_id", sa.UUID(), nullable=True))
    op.add_column("ai_step_executions", sa.Column("retryable", sa.Boolean(), nullable=False))
    op.add_column("ai_step_executions", sa.Column("error_summary", sa.Text(), nullable=True))
    op.add_column(
        "ai_step_executions", sa.Column("provider_name", sa.String(length=50), nullable=True)
    )
    op.add_column(
        "ai_step_executions", sa.Column("model_name", sa.String(length=100), nullable=True)
    )
    op.add_column("ai_step_executions", sa.Column("usage_snapshot", sa.JSON(), nullable=True))
    op.add_column("ai_step_executions", sa.Column("duration_ms", sa.Integer(), nullable=True))
    op.create_index(
        op.f("ix_ai_step_executions_available_at"),
        "ai_step_executions",
        ["available_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ai_step_executions_claim_expires_at"),
        "ai_step_executions",
        ["claim_expires_at"],
        unique=False,
    )
    op.create_foreign_key(
        "fk_ai_step_executions_retry_of_id",
        "ai_step_executions",
        "ai_step_executions",
        ["retry_of_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_ai_step_executions_retry_of_id", "ai_step_executions", type_="foreignkey"
    )
    op.drop_index(op.f("ix_ai_step_executions_claim_expires_at"), table_name="ai_step_executions")
    op.drop_index(op.f("ix_ai_step_executions_available_at"), table_name="ai_step_executions")
    op.drop_column("ai_step_executions", "duration_ms")
    op.drop_column("ai_step_executions", "usage_snapshot")
    op.drop_column("ai_step_executions", "model_name")
    op.drop_column("ai_step_executions", "provider_name")
    op.drop_column("ai_step_executions", "error_summary")
    op.drop_column("ai_step_executions", "retryable")
    op.drop_column("ai_step_executions", "retry_of_id")
    op.drop_column("ai_step_executions", "claim_version")
    op.drop_column("ai_step_executions", "claim_expires_at")
    op.drop_column("ai_step_executions", "claim_owner")
    op.drop_column("ai_step_executions", "available_at")
    op.drop_column("ai_step_executions", "input_summary")
    op.drop_column("ai_step_executions", "input_snapshot")
    op.drop_column("ai_step_executions", "node_name")
    op.drop_column("ai_step_executions", "node_type")
    op.drop_constraint(
        "fk_ai_capability_runs_cancel_requested_by_users", "ai_capability_runs", type_="foreignkey"
    )
    op.drop_constraint(
        "uq_ai_capability_runs_proj_init_idempotency", "ai_capability_runs", type_="unique"
    )
    op.drop_column("ai_capability_runs", "error_summary")
    op.drop_column("ai_capability_runs", "error_code")
    op.drop_column("ai_capability_runs", "usage_snapshot")
    op.drop_column("ai_capability_runs", "deadline_at")
    op.drop_column("ai_capability_runs", "final_output_snapshot_id")
    op.drop_column("ai_capability_runs", "cancel_requested_by")
    op.drop_column("ai_capability_runs", "cancel_requested_at")
    op.drop_column("ai_capability_runs", "next_event_sequence")
    op.drop_column("ai_capability_runs", "request_fingerprint")
    op.drop_column("ai_capability_runs", "idempotency_key")
    op.drop_column("ai_capability_runs", "execution_snapshot_hash")
    op.drop_column("ai_capability_runs", "execution_snapshot")
    op.drop_column("ai_capability_runs", "run_mode")
    op.drop_table("ai_step_output_snapshots")
    op.drop_table("ai_run_events")
    op.drop_table("ai_human_gate_actions")
    # ### end Alembic commands ###
