"""add_p1_sync_registry_tables

Revision ID: 3265b622f4b4
Revises: d3a37b5abb6d
Create Date: 2026-07-22 08:03:44.234933
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "3265b622f4b4"
down_revision: str | None = "d3a37b5abb6d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "external_agent_tokens",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("token_prefix", sa.String(length=50), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("namespace_scope", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=200), nullable=True),
        sa.Column("is_revoked", sa.Boolean(), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name="fk_ext_agent_tokens_created_by_users",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name="fk_ext_agent_tokens_project_id_projects",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_external_agent_tokens")),
        sa.UniqueConstraint("token_hash", name="uq_external_agent_tokens_token_hash"),
    )
    op.create_index(
        op.f("ix_external_agent_tokens_token_hash"),
        "external_agent_tokens",
        ["token_hash"],
        unique=False,
    )
    op.create_table(
        "external_agents",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("connection_name", sa.String(length=100), nullable=False),
        sa.Column("client_name", sa.String(length=100), nullable=False),
        sa.Column("client_version", sa.String(length=50), nullable=False),
        sa.Column("platform", sa.String(length=50), nullable=False),
        sa.Column("protocol_version", sa.String(length=20), nullable=False),
        sa.Column("last_active_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name="fk_external_agents_project_id_projects",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_external_agents")),
        sa.UniqueConstraint("project_id", name="uq_external_agents_project_id"),
    )
    op.create_table(
        "ai_capability_packages",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("capability_version_id", sa.UUID(), nullable=False),
        sa.Column("package_fingerprint", sa.String(length=128), nullable=False),
        sa.Column("validation_report", sa.JSON(), nullable=False),
        sa.Column("files_snapshot", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["capability_version_id"],
            ["ai_capability_versions.id"],
            name="fk_ai_cap_packages_cap_ver_id_ai_cap_vers",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_capability_packages")),
        sa.UniqueConstraint(
            "capability_version_id", name="uq_ai_capability_packages_capability_version_id"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("ai_capability_packages")
    op.drop_table("external_agents")
    op.drop_index(op.f("ix_external_agent_tokens_token_hash"), table_name="external_agent_tokens")
    op.drop_table("external_agent_tokens")
    # ### end Alembic commands ###
