"""create test_case_mindmaps table

Revision ID: 4e89f0a0230e
Revises: 65482bc04697
Create Date: 2026-07-20 18:03:44.874047
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "4e89f0a0230e"
down_revision: str | None = "65482bc04697"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "test_case_mindmaps",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("task_id", sa.Uuid(), nullable=True),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_test_case_mindmaps_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["test_tasks.id"],
            name=op.f("fk_test_case_mindmaps_task_id_test_tasks"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_test_case_mindmaps")),
        sa.UniqueConstraint("task_id", name=op.f("uq_test_case_mindmaps_task_id")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("test_case_mindmaps")
    # ### end Alembic commands ###
