"""create_m05_tables

Revision ID: 65482bc04697
Revises: f6084f4ff89c
Create Date: 2026-07-20 14:10:16.724807
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "65482bc04697"
down_revision: str | None = "f6084f4ff89c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "case_modules",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("parent_id", sa.Uuid(), nullable=True),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["case_modules.id"],
            name=op.f("fk_case_modules_parent_id_case_modules"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_case_modules_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_case_modules")),
        sa.UniqueConstraint(
            "project_id", "parent_id", "name", name="uq_case_modules_project_parent_name"
        ),
    )
    op.create_index(op.f("ix_case_modules_parent_id"), "case_modules", ["parent_id"], unique=False)
    op.create_index(
        op.f("ix_case_modules_project_id"), "case_modules", ["project_id"], unique=False
    )
    op.create_table(
        "case_number_sequences",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("current_value", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_case_number_sequences_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("project_id", name=op.f("pk_case_number_sequences")),
    )
    op.create_table(
        "test_cases",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("case_no", sa.String(length=50), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("precondition", sa.Text(), nullable=True),
        sa.Column("priority", sa.String(length=50), nullable=False),
        sa.Column("case_type", sa.String(length=50), nullable=False),
        sa.Column("tags_json", sa.JSON(), nullable=False),
        sa.Column("test_data_note", sa.Text(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("source_task_id", sa.Uuid(), nullable=True),
        sa.Column("current_revision_id", sa.Uuid(), nullable=True),
        sa.Column("row_version", sa.BigInteger(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.Uuid(), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("updated_by", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_test_cases_created_by_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["deleted_by"],
            ["users.id"],
            name=op.f("fk_test_cases_deleted_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_test_cases_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_task_id"],
            ["test_tasks.id"],
            name=op.f("fk_test_cases_source_task_id_test_tasks"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
            name=op.f("fk_test_cases_updated_by_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_test_cases")),
        sa.UniqueConstraint("project_id", "case_no", name="uq_test_cases_project_case_no"),
    )
    op.create_index(op.f("ix_test_cases_project_id"), "test_cases", ["project_id"], unique=False)
    op.create_index(
        op.f("ix_test_cases_source_task_id"), "test_cases", ["source_task_id"], unique=False
    )
    op.create_table(
        "test_case_module_relations",
        sa.Column("case_id", sa.Uuid(), nullable=False),
        sa.Column("module_id", sa.Uuid(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["test_cases.id"],
            name=op.f("fk_test_case_module_relations_case_id_test_cases"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_test_case_module_relations_created_by_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["module_id"],
            ["case_modules.id"],
            name=op.f("fk_test_case_module_relations_module_id_case_modules"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("case_id", "module_id", name=op.f("pk_test_case_module_relations")),
    )
    op.create_table(
        "test_case_revisions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("case_id", sa.Uuid(), nullable=False),
        sa.Column("revision_no", sa.Integer(), nullable=False),
        sa.Column("snapshot", sa.JSON(), nullable=False),
        sa.Column("snapshot_hash", sa.String(length=100), nullable=False),
        sa.Column("change_summary", sa.JSON(), nullable=False),
        sa.Column("edit_session_id", sa.Uuid(), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["test_cases.id"],
            name=op.f("fk_test_case_revisions_case_id_test_cases"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_test_case_revisions_created_by_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_test_case_revisions")),
        sa.UniqueConstraint(
            "case_id", "revision_no", name="uq_test_case_revisions_case_revision_no"
        ),
    )
    op.create_index(
        op.f("ix_test_case_revisions_case_id"), "test_case_revisions", ["case_id"], unique=False
    )
    op.create_table(
        "test_case_steps",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("case_id", sa.Uuid(), nullable=False),
        sa.Column("step_order", sa.Integer(), nullable=False),
        sa.Column("action", sa.Text(), nullable=False),
        sa.Column("expected_result", sa.Text(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["test_cases.id"],
            name=op.f("fk_test_case_steps_case_id_test_cases"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_test_case_steps")),
        sa.UniqueConstraint("case_id", "step_order", name="uq_test_case_steps_case_step_order"),
    )
    op.create_index(
        op.f("ix_test_case_steps_case_id"), "test_case_steps", ["case_id"], unique=False
    )
    op.create_table(
        "test_case_edit_sessions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("case_id", sa.Uuid(), nullable=False),
        sa.Column("actor_id", sa.Uuid(), nullable=False),
        sa.Column("base_revision_id", sa.Uuid(), nullable=True),
        sa.Column("base_row_version", sa.BigInteger(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("dirty_fields", sa.JSON(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_activity_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finalized_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["users.id"],
            name=op.f("fk_test_case_edit_sessions_actor_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["base_revision_id"],
            ["test_case_revisions.id"],
            name=op.f("fk_test_case_edit_sessions_base_revision_id_test_case_revisions"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["test_cases.id"],
            name=op.f("fk_test_case_edit_sessions_case_id_test_cases"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_test_case_edit_sessions")),
    )
    op.create_index(
        op.f("ix_test_case_edit_sessions_case_id"),
        "test_case_edit_sessions",
        ["case_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_test_case_edit_sessions_case_id"), table_name="test_case_edit_sessions")
    op.drop_table("test_case_edit_sessions")
    op.drop_index(op.f("ix_test_case_steps_case_id"), table_name="test_case_steps")
    op.drop_table("test_case_steps")
    op.drop_index(op.f("ix_test_case_revisions_case_id"), table_name="test_case_revisions")
    op.drop_table("test_case_revisions")
    op.drop_table("test_case_module_relations")
    op.drop_index(op.f("ix_test_cases_source_task_id"), table_name="test_cases")
    op.drop_index(op.f("ix_test_cases_project_id"), table_name="test_cases")
    op.drop_table("test_cases")
    op.drop_table("case_number_sequences")
    op.drop_index(op.f("ix_case_modules_project_id"), table_name="case_modules")
    op.drop_index(op.f("ix_case_modules_parent_id"), table_name="case_modules")
    op.drop_table("case_modules")
    # ### end Alembic commands ###
