"""create_m03_tables

Revision ID: 7c55e6d20ba6
Revises: 1df83d9054f8
Create Date: 2026-07-20 11:58:02.430306
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '7c55e6d20ba6'
down_revision: str | None = '1df83d9054f8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_tasks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('version_id', sa.Uuid(), nullable=False),
    sa.Column('task_no', sa.String(length=100), nullable=False),
    sa.Column('task_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('priority', sa.String(length=50), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('planned_start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('planned_end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actual_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completion_count', sa.Integer(), nullable=False),
    sa.Column('completion_note', sa.Text(), nullable=True),
    sa.Column('test_goal', sa.Text(), nullable=True),
    sa.Column('excluded_scope', sa.Text(), nullable=True),
    sa.Column('tags_json', sa.JSON(), nullable=True),
    sa.Column('previous_status', sa.String(length=50), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_test_tasks_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_test_tasks_owner_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_test_tasks_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_test_tasks_updated_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['version_id'], ['versions.id'], name=op.f('fk_test_tasks_version_id_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_test_tasks')),
    sa.UniqueConstraint('project_id', 'task_no', name='uq_test_tasks_project_task_no')
    )
    op.create_index(op.f('ix_test_tasks_project_id'), 'test_tasks', ['project_id'], unique=False)
    op.create_index(op.f('ix_test_tasks_version_id'), 'test_tasks', ['version_id'], unique=False)
    op.create_table('test_task_blockages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('reason_code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('blocked_by', sa.Uuid(), nullable=True),
    sa.Column('blocked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_by', sa.Uuid(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['blocked_by'], ['users.id'], name=op.f('fk_test_task_blockages_blocked_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_test_task_blockages_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], name=op.f('fk_test_task_blockages_resolved_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['test_tasks.id'], name=op.f('fk_test_task_blockages_task_id_test_tasks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_test_task_blockages'))
    )
    op.create_index(op.f('ix_test_task_blockages_project_id'), 'test_task_blockages', ['project_id'], unique=False)
    op.create_index(op.f('ix_test_task_blockages_task_id'), 'test_task_blockages', ['task_id'], unique=False)
    op.create_table('test_task_participants',
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('added_by', sa.Uuid(), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['added_by'], ['users.id'], name=op.f('fk_test_task_participants_added_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['test_tasks.id'], name=op.f('fk_test_task_participants_task_id_test_tasks'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_test_task_participants_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('task_id', 'user_id', name=op.f('pk_test_task_participants'))
    )
    op.create_table('test_task_requirements',
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('requirement_id', sa.Uuid(), nullable=False),
    sa.Column('linked_by', sa.Uuid(), nullable=True),
    sa.Column('linked_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['linked_by'], ['users.id'], name=op.f('fk_test_task_requirements_linked_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], name=op.f('fk_test_task_requirements_requirement_id_requirements'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['test_tasks.id'], name=op.f('fk_test_task_requirements_task_id_test_tasks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('task_id', 'requirement_id', name=op.f('pk_test_task_requirements'))
    )
    op.create_table('test_task_status_history',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('from_status', sa.String(length=50), nullable=False),
    sa.Column('to_status', sa.String(length=50), nullable=False),
    sa.Column('reason_code', sa.String(length=50), nullable=True),
    sa.Column('reason_text', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('request_id', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_test_task_status_history_actor_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_test_task_status_history_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['test_tasks.id'], name=op.f('fk_test_task_status_history_task_id_test_tasks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_test_task_status_history'))
    )
    op.create_index(op.f('ix_test_task_status_history_project_id'), 'test_task_status_history', ['project_id'], unique=False)
    op.create_index(op.f('ix_test_task_status_history_task_id'), 'test_task_status_history', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_task_status_history_task_id'), table_name='test_task_status_history')
    op.drop_index(op.f('ix_test_task_status_history_project_id'), table_name='test_task_status_history')
    op.drop_table('test_task_status_history')
    op.drop_table('test_task_requirements')
    op.drop_table('test_task_participants')
    op.drop_index(op.f('ix_test_task_blockages_task_id'), table_name='test_task_blockages')
    op.drop_index(op.f('ix_test_task_blockages_project_id'), table_name='test_task_blockages')
    op.drop_table('test_task_blockages')
    op.drop_index(op.f('ix_test_tasks_version_id'), table_name='test_tasks')
    op.drop_index(op.f('ix_test_tasks_project_id'), table_name='test_tasks')
    op.drop_table('test_tasks')
    # ### end Alembic commands ###
