"""[REQ-10006] add_p3_revision_and_feedback_tables

Revision ID: 80b153ff6bb9
Revises: 30afeeaaf04a
Create Date: 2026-07-22 09:05:11.439483
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "80b153ff6bb9"
down_revision: str | None = "30afeeaaf04a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ai_artifact_items",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("producer_node_id", sa.String(length=64), nullable=False),
        sa.Column("artifact_type", sa.String(length=64), nullable=False),
        sa.Column("stable_key", sa.String(length=128), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name="fk_ai_artifact_items_created_by",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name="fk_ai_artifact_items_project_id",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["ai_capability_runs.id"],
            name="fk_ai_artifact_items_run_id",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_artifact_items")),
        sa.UniqueConstraint(
            "run_id", "producer_node_id", "stable_key", name="uq_ai_artifact_items_run_node_key"
        ),
    )
    op.create_table(
        "ai_artifact_revisions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("artifact_item_id", sa.UUID(), nullable=False),
        sa.Column("revision_no", sa.Integer(), nullable=False),
        sa.Column("content", sa.JSON(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("source_step_execution_id", sa.UUID(), nullable=True),
        sa.Column("source_regeneration_request_id", sa.UUID(), nullable=True),
        sa.Column("schema_snapshot", sa.JSON(), nullable=True),
        sa.Column("validation_snapshot", sa.JSON(), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "revision_no > 0",
            name=op.f("ck_ai_artifact_revisions_ck_ai_artifact_revisions_no_positive"),
        ),
        sa.ForeignKeyConstraint(
            ["artifact_item_id"],
            ["ai_artifact_items.id"],
            name="fk_ai_artifact_revisions_item_id",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name="fk_ai_artifact_revisions_created_by",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name="fk_ai_artifact_revisions_project_id",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_step_execution_id"],
            ["ai_step_executions.id"],
            name="fk_ai_artifact_revisions_step_exec",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_artifact_revisions")),
        sa.UniqueConstraint(
            "artifact_item_id", "revision_no", name="uq_ai_artifact_revisions_item_no"
        ),
    )
    op.create_table(
        "ai_artifact_set_revisions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("producer_node_id", sa.String(length=64), nullable=False),
        sa.Column("set_revision_no", sa.Integer(), nullable=False),
        sa.Column("base_set_revision_id", sa.UUID(), nullable=True),
        sa.Column("source_step_execution_id", sa.UUID(), nullable=True),
        sa.Column("source_regeneration_request_id", sa.UUID(), nullable=True),
        sa.Column("input_context_snapshot_id", sa.UUID(), nullable=True),
        sa.Column("input_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("set_hash", sa.String(length=64), nullable=False),
        sa.Column("item_count", sa.Integer(), nullable=False),
        sa.Column("review_status", sa.String(length=32), nullable=False),
        sa.Column("validation_status", sa.String(length=32), nullable=False),
        sa.Column("validation_snapshot", sa.JSON(), nullable=True),
        sa.Column("decision_by", sa.UUID(), nullable=True),
        sa.Column("decision_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("decision_reason", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "item_count >= 0",
            name=op.f("ck_ai_artifact_set_revisions_ck_ai_set_revisions_count_nonnegative"),
        ),
        sa.CheckConstraint(
            "set_revision_no > 0",
            name=op.f("ck_ai_artifact_set_revisions_ck_ai_set_revisions_no_positive"),
        ),
        sa.ForeignKeyConstraint(
            ["base_set_revision_id"],
            ["ai_artifact_set_revisions.id"],
            name="fk_ai_set_revisions_base_id",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["decision_by"],
            ["users.id"],
            name="fk_ai_set_revisions_decision_by",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name="fk_ai_set_revisions_project_id",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["ai_capability_runs.id"],
            name="fk_ai_set_revisions_run_id",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_step_execution_id"],
            ["ai_step_executions.id"],
            name="fk_ai_set_revisions_step_exec",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_artifact_set_revisions")),
        sa.UniqueConstraint(
            "run_id", "producer_node_id", "set_revision_no", name="uq_ai_set_revisions_run_node_no"
        ),
    )
    op.create_table(
        "ai_artifact_revision_parents",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("child_revision_id", sa.UUID(), nullable=False),
        sa.Column("parent_revision_id", sa.UUID(), nullable=False),
        sa.Column("relation_type", sa.String(length=32), nullable=False),
        sa.Column("parent_order", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["child_revision_id"],
            ["ai_artifact_revisions.id"],
            name="fk_ai_rev_parents_child",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["parent_revision_id"],
            ["ai_artifact_revisions.id"],
            name="fk_ai_rev_parents_parent",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_artifact_revision_parents")),
        sa.UniqueConstraint(
            "child_revision_id",
            "parent_revision_id",
            name="uq_ai_artifact_rev_parents_child_parent",
        ),
    )
    op.create_table(
        "ai_artifact_set_revision_members",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("set_revision_id", sa.UUID(), nullable=False),
        sa.Column("artifact_item_id", sa.UUID(), nullable=False),
        sa.Column("artifact_revision_id", sa.UUID(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "position >= 0",
            name=op.f("ck_ai_artifact_set_revision_members_ck_ai_set_members_pos_nonnegative"),
        ),
        sa.ForeignKeyConstraint(
            ["artifact_item_id"],
            ["ai_artifact_items.id"],
            name="fk_ai_set_members_item_id",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["artifact_revision_id"],
            ["ai_artifact_revisions.id"],
            name="fk_ai_set_members_rev_id",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["set_revision_id"],
            ["ai_artifact_set_revisions.id"],
            name="fk_ai_set_members_set_id",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_artifact_set_revision_members")),
        sa.UniqueConstraint(
            "set_revision_id", "artifact_item_id", name="uq_ai_set_members_set_item"
        ),
        sa.UniqueConstraint("set_revision_id", "position", name="uq_ai_set_members_set_position"),
    )
    op.create_table(
        "ai_current_accepted_revision_sets",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("node_id", sa.String(length=64), nullable=False),
        sa.Column("current_set_revision_id", sa.UUID(), nullable=False),
        sa.Column("acceptance_sequence", sa.Integer(), nullable=False),
        sa.Column("row_version", sa.Integer(), nullable=False),
        sa.Column("accepted_by", sa.UUID(), nullable=True),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("freshness_status", sa.String(length=32), nullable=False),
        sa.Column("validation_status", sa.String(length=32), nullable=False),
        sa.Column("rerun_required", sa.Boolean(), nullable=False),
        sa.Column("state_reasons", sa.JSON(), nullable=True),
        sa.Column("materialized_input_fingerprint", sa.String(length=64), nullable=True),
        sa.Column("expected_input_fingerprint", sa.String(length=64), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["accepted_by"],
            ["users.id"],
            name="fk_ai_current_sets_accepted_by",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["current_set_revision_id"],
            ["ai_artifact_set_revisions.id"],
            name="fk_ai_current_sets_set_id",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name="fk_ai_current_sets_project_id",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["ai_capability_runs.id"],
            name="fk_ai_current_sets_run_id",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_current_accepted_revision_sets")),
        sa.UniqueConstraint("run_id", "node_id", name="uq_ai_current_accepted_sets_run_node"),
    )
    op.create_table(
        "ai_feedback",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("target_type", sa.String(length=32), nullable=False),
        sa.Column("target_item_id", sa.UUID(), nullable=True),
        sa.Column("target_revision_id", sa.UUID(), nullable=True),
        sa.Column("target_step_execution_id", sa.UUID(), nullable=True),
        sa.Column("json_pointer", sa.String(length=256), nullable=True),
        sa.Column("category", sa.String(length=64), nullable=False),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("resolved_by", sa.UUID(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name="fk_ai_feedback_created_by", ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], name="fk_ai_feedback_project_id", ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["resolved_by"], ["users.id"], name="fk_ai_feedback_resolved_by", ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["ai_capability_runs.id"], name="fk_ai_feedback_run_id", ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["target_item_id"],
            ["ai_artifact_items.id"],
            name="fk_ai_feedback_item_id",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["target_revision_id"],
            ["ai_artifact_revisions.id"],
            name="fk_ai_feedback_rev_id",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["target_step_execution_id"],
            ["ai_step_executions.id"],
            name="fk_ai_feedback_step_exec",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_feedback")),
    )
    op.create_table(
        "ai_field_locks",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("node_id", sa.String(length=64), nullable=False),
        sa.Column("artifact_item_id", sa.UUID(), nullable=False),
        sa.Column("anchor_revision_id", sa.UUID(), nullable=False),
        sa.Column("json_pointer", sa.String(length=256), nullable=False),
        sa.Column("value_hash", sa.String(length=64), nullable=False),
        sa.Column("last_verified_revision_id", sa.UUID(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("row_version", sa.Integer(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("released_by", sa.UUID(), nullable=True),
        sa.Column("released_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["anchor_revision_id"],
            ["ai_artifact_revisions.id"],
            name="fk_ai_field_locks_anchor_rev",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["artifact_item_id"],
            ["ai_artifact_items.id"],
            name="fk_ai_field_locks_item_id",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name="fk_ai_field_locks_created_by", ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["last_verified_revision_id"],
            ["ai_artifact_revisions.id"],
            name="fk_ai_field_locks_last_rev",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name="fk_ai_field_locks_project_id",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["released_by"], ["users.id"], name="fk_ai_field_locks_released_by", ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["ai_capability_runs.id"],
            name="fk_ai_field_locks_run_id",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_field_locks")),
    )
    op.create_table(
        "ai_regeneration_requests",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("node_id", sa.String(length=64), nullable=False),
        sa.Column("base_set_revision_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("request_snapshot", sa.JSON(), nullable=False),
        sa.Column("request_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=True),
        sa.Column("requested_by", sa.UUID(), nullable=True),
        sa.Column("result_set_revision_id", sa.UUID(), nullable=True),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("error_summary", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["base_set_revision_id"],
            ["ai_artifact_set_revisions.id"],
            name="fk_ai_regen_reqs_base_set",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], name="fk_ai_regen_reqs_project_id", ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["requested_by"],
            ["users.id"],
            name="fk_ai_regen_reqs_requested_by",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["result_set_revision_id"],
            ["ai_artifact_set_revisions.id"],
            name="fk_ai_regen_reqs_result_set",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["ai_capability_runs.id"],
            name="fk_ai_regen_reqs_run_id",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_regeneration_requests")),
    )
    op.create_table(
        "ai_context_snapshots",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("node_id", sa.String(length=64), nullable=False),
        sa.Column("purpose", sa.String(length=32), nullable=False),
        sa.Column("source_step_execution_id", sa.UUID(), nullable=True),
        sa.Column("source_regeneration_request_id", sa.UUID(), nullable=True),
        sa.Column("content", sa.JSON(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("input_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("fingerprint_algorithm", sa.String(length=64), nullable=False),
        sa.Column("upstream_manifest", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name="fk_ai_context_snapshots_project_id",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["ai_capability_runs.id"],
            name="fk_ai_context_snapshots_run_id",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_regeneration_request_id"],
            ["ai_regeneration_requests.id"],
            name="fk_ai_context_snapshots_regen_req",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_step_execution_id"],
            ["ai_step_executions.id"],
            name="fk_ai_context_snapshots_step_exec",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_context_snapshots")),
    )
    op.create_table(
        "ai_regeneration_request_feedback",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("regeneration_request_id", sa.UUID(), nullable=False),
        sa.Column("feedback_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["feedback_id"], ["ai_feedback.id"], name="fk_ai_regen_fb_fb_id", ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["regeneration_request_id"],
            ["ai_regeneration_requests.id"],
            name="fk_ai_regen_fb_req_id",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_regeneration_request_feedback")),
    )
    op.create_table(
        "ai_regeneration_request_items",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("regeneration_request_id", sa.UUID(), nullable=False),
        sa.Column("artifact_item_id", sa.UUID(), nullable=False),
        sa.Column("base_revision_id", sa.UUID(), nullable=False),
        sa.Column("target_ref", sa.String(length=128), nullable=False),
        sa.ForeignKeyConstraint(
            ["artifact_item_id"],
            ["ai_artifact_items.id"],
            name="fk_ai_regen_items_item_id",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["base_revision_id"],
            ["ai_artifact_revisions.id"],
            name="fk_ai_regen_items_base_rev",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["regeneration_request_id"],
            ["ai_regeneration_requests.id"],
            name="fk_ai_regen_items_req_id",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_regeneration_request_items")),
    )
    op.create_table(
        "ai_dependency_edges",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("upstream_node_id", sa.String(length=64), nullable=False),
        sa.Column("upstream_set_revision_id", sa.UUID(), nullable=False),
        sa.Column("downstream_node_id", sa.String(length=64), nullable=False),
        sa.Column("downstream_context_snapshot_id", sa.UUID(), nullable=False),
        sa.Column("downstream_step_execution_id", sa.UUID(), nullable=True),
        sa.Column("downstream_output_set_revision_id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["downstream_context_snapshot_id"],
            ["ai_context_snapshots.id"],
            name="fk_ai_dep_edges_down_ctx_id",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["downstream_output_set_revision_id"],
            ["ai_artifact_set_revisions.id"],
            name="fk_ai_dep_edges_down_out_set",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["downstream_step_execution_id"],
            ["ai_step_executions.id"],
            name="fk_ai_dep_edges_down_step_id",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], name="fk_ai_dep_edges_project_id", ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["ai_capability_runs.id"],
            name="fk_ai_dep_edges_run_id",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["upstream_set_revision_id"],
            ["ai_artifact_set_revisions.id"],
            name="fk_ai_dep_edges_up_set_id",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_dependency_edges")),
    )
    op.add_column(
        "ai_step_executions", sa.Column("input_context_snapshot_id", sa.UUID(), nullable=True)
    )
    op.add_column(
        "ai_step_executions", sa.Column("output_revision_set_id", sa.UUID(), nullable=True)
    )
    op.add_column(
        "ai_step_executions", sa.Column("execution_reason", sa.String(length=32), nullable=False)
    )
    op.add_column(
        "ai_step_executions", sa.Column("context_generation", sa.Integer(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ai_step_executions", "context_generation")
    op.drop_column("ai_step_executions", "execution_reason")
    op.drop_column("ai_step_executions", "output_revision_set_id")
    op.drop_column("ai_step_executions", "input_context_snapshot_id")
    op.drop_table("ai_dependency_edges")
    op.drop_table("ai_regeneration_request_items")
    op.drop_table("ai_regeneration_request_feedback")
    op.drop_table("ai_context_snapshots")
    op.drop_table("ai_regeneration_requests")
    op.drop_table("ai_field_locks")
    op.drop_table("ai_feedback")
    op.drop_table("ai_current_accepted_revision_sets")
    op.drop_table("ai_artifact_set_revision_members")
    op.drop_table("ai_artifact_revision_parents")
    op.drop_table("ai_artifact_set_revisions")
    op.drop_table("ai_artifact_revisions")
    op.drop_table("ai_artifact_items")
    # ### end Alembic commands ###
