"""add M09 AI capability foundation tables

Revision ID: d3a37b5abb6d
Revises: 4e89f0a0230e
Create Date: 2026-07-21 22:05:24.586088
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "d3a37b5abb6d"
down_revision: str | None = "4e89f0a0230e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ai_capabilities",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("namespace", sa.String(length=100), nullable=False),
        sa.Column("code", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("category", sa.String(length=100), nullable=False),
        sa.Column("scope", sa.String(length=20), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=True),
        sa.Column("current_published_version_id", sa.UUID(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "(scope = 'OFFICIAL' AND project_id IS NULL) OR (scope = 'PROJECT' AND project_id IS NOT NULL)",
            name=op.f("ck_ai_capabilities_ck_ai_capabilities_scope_project_nullability"),
        ),
        sa.CheckConstraint(
            "scope IN ('OFFICIAL', 'PROJECT')", name=op.f("ck_ai_capabilities_scope_values")
        ),
        sa.CheckConstraint(
            "status IN ('ACTIVE', 'ARCHIVED')", name=op.f("ck_ai_capabilities_status_values")
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name="fk_ai_capabilities_project_id_projects",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_capabilities")),
        sa.UniqueConstraint("namespace", "code", name="uq_ai_capabilities_namespace_code"),
    )
    op.create_table(
        "ai_capability_versions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("capability_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("package_fingerprint", sa.String(length=128), nullable=True),
        sa.Column("compatibility_level", sa.String(length=50), nullable=True),
        sa.Column("workflow_snapshot", sa.JSON(), nullable=True),
        sa.Column("input_schema", sa.JSON(), nullable=True),
        sa.Column("output_schema", sa.JSON(), nullable=True),
        sa.Column("created_source", sa.String(length=50), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('SYNCED_DRAFT', 'VALIDATING', 'IN_REVIEW', 'PUBLISHED', 'REJECTED', 'DEPRECATED', 'ROLLED_BACK')",
            name=op.f("ck_ai_capability_versions_status_values"),
        ),
        sa.ForeignKeyConstraint(
            ["capability_id"],
            ["ai_capabilities.id"],
            name="fk_ai_capability_versions_capability_id_ai_capabilities",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name="fk_ai_capability_versions_created_by_users",
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_capability_versions")),
        sa.UniqueConstraint(
            "capability_id", "version", name="uq_ai_capability_versions_capability_version"
        ),
    )
    op.create_table(
        "ai_capability_runs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("capability_version_id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("initiator_id", sa.UUID(), nullable=True),
        sa.Column("trace_id", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("input_snapshot", sa.JSON(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('PENDING', 'RUNNING', 'WAITING_HUMAN', 'WAITING_EXTERNAL_AGENT', 'WAITING_RETRY', 'SUCCEEDED', 'FAILED', 'CANCELLED')",
            name=op.f("ck_ai_capability_runs_status_values"),
        ),
        sa.ForeignKeyConstraint(
            ["capability_version_id"],
            ["ai_capability_versions.id"],
            name="fk_ai_capability_runs_capability_version_id",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["initiator_id"],
            ["users.id"],
            name="fk_ai_capability_runs_initiator_id_users",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name="fk_ai_capability_runs_project_id_projects",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_capability_runs")),
    )
    op.create_index(
        op.f("ix_ai_capability_runs_trace_id"), "ai_capability_runs", ["trace_id"], unique=True
    )
    op.create_table(
        "ai_step_executions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("node_id", sa.String(length=100), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("input_fingerprint", sa.String(length=128), nullable=True),
        sa.Column("error_code", sa.String(length=100), nullable=True),
        sa.Column("safety_summary", sa.String(length=500), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('PENDING', 'RUNNING', 'WAITING_HUMAN', 'WAITING_EXTERNAL_AGENT', 'WAITING_RETRY', 'SUCCEEDED', 'FAILED', 'CANCELLED', 'SKIPPED')",
            name=op.f("ck_ai_step_executions_status_values"),
        ),
        sa.CheckConstraint("attempt > 0", name=op.f("ck_ai_step_executions_attempt_positive")),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["ai_capability_runs.id"],
            name="fk_ai_step_executions_run_id_ai_capability_runs",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_step_executions")),
        sa.UniqueConstraint(
            "run_id", "node_id", "attempt", name="uq_ai_step_executions_run_node_attempt"
        ),
    )

    # 具名并后置创建 current_published_version_id 循环外键
    op.create_foreign_key(
        "fk_ai_capabilities_curr_ver_id",
        "ai_capabilities",
        "ai_capability_versions",
        ["current_published_version_id"],
        ["id"],
        ondelete="RESTRICT",
    )


def downgrade() -> None:
    # 显式后置解绑循环外键
    op.drop_constraint(
        "fk_ai_capabilities_curr_ver_id",
        "ai_capabilities",
        type_="foreignkey",
    )
    op.drop_table("ai_step_executions")
    op.drop_index(op.f("ix_ai_capability_runs_trace_id"), table_name="ai_capability_runs")
    op.drop_table("ai_capability_runs")
    op.drop_table("ai_capability_versions")
    op.drop_table("ai_capabilities")
    # ### end Alembic commands ###
