"""add_unique_constraint_to_test_task_requirements

Revision ID: f6084f4ff89c
Revises: 7c55e6d20ba6
Create Date: 2026-07-20 14:05:51.915817
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'f6084f4ff89c'
down_revision: str | None = '7c55e6d20ba6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_test_task_requirements_task_id', 'test_task_requirements', ['task_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_test_task_requirements_task_id', 'test_task_requirements', type_='unique')
    # ### end Alembic commands ###
