from enum import StrEnum


class CapabilityScope(StrEnum):
    """AI 能力作用域"""

    OFFICIAL = "OFFICIAL"
    PROJECT = "PROJECT"


class AICapabilityStatus(StrEnum):
    """AI 能力全局状态"""

    ACTIVE = "ACTIVE"
    ARCHIVED = "ARCHIVED"


class CapabilityVersionStatus(StrEnum):
    """AI 能力版本状态"""

    SYNCED_DRAFT = "SYNCED_DRAFT"
    VALIDATING = "VALIDATING"
    IN_REVIEW = "IN_REVIEW"
    PUBLISHED = "PUBLISHED"
    REJECTED = "REJECTED"
    DEPRECATED = "DEPRECATED"
    ROLLED_BACK = "ROLLED_BACK"


class CapabilityRunStatus(StrEnum):
    """AI 能力运行记录状态"""

    PENDING = "PENDING"
    RUNNING = "RUNNING"
    WAITING_HUMAN = "WAITING_HUMAN"
    WAITING_EXTERNAL_AGENT = "WAITING_EXTERNAL_AGENT"
    WAITING_RETRY = "WAITING_RETRY"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class StepExecutionStatus(StrEnum):
    """AI 步骤执行状态 (包含 SKIPPED)"""

    PENDING = "PENDING"
    RUNNING = "RUNNING"
    WAITING_HUMAN = "WAITING_HUMAN"
    WAITING_EXTERNAL_AGENT = "WAITING_EXTERNAL_AGENT"
    WAITING_RETRY = "WAITING_RETRY"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"
    SKIPPED = "SKIPPED"


class AIRunMode(StrEnum):
    """AI 运行模式"""

    NORMAL = "NORMAL"
    PREVIEW = "PREVIEW"


class ExecNodeType(StrEnum):
    """Workflow 节点执行类型"""

    SKILL = "SKILL"
    TRANSFORM = "TRANSFORM"
    VALIDATOR = "VALIDATOR"
    HUMAN = "HUMAN"


class HumanAction(StrEnum):
    """Human 节点决策动作"""

    CONTINUE = "CONTINUE"
    REJECT = "REJECT"


class AIRunEventType(StrEnum):
    """AI Run 持久化事件类型"""

    RUN_CREATED = "RUN_CREATED"
    RUN_STARTED = "RUN_STARTED"
    RUN_WAITING_HUMAN = "RUN_WAITING_HUMAN"
    RUN_WAITING_RETRY = "RUN_WAITING_RETRY"
    RUN_CANCEL_REQUESTED = "RUN_CANCEL_REQUESTED"
    RUN_CANCELLED = "RUN_CANCELLED"
    RUN_SUCCEEDED = "RUN_SUCCEEDED"
    RUN_FAILED = "RUN_FAILED"
    STEP_QUEUED = "STEP_QUEUED"
    STEP_STARTED = "STEP_STARTED"
    STEP_WAITING_HUMAN = "STEP_WAITING_HUMAN"
    HUMAN_DECISION_SUBMITTED = "HUMAN_DECISION_SUBMITTED"
    STEP_RETRY_SCHEDULED = "STEP_RETRY_SCHEDULED"
    STEP_SUCCEEDED = "STEP_SUCCEEDED"
    STEP_FAILED = "STEP_FAILED"
    STEP_CANCELLED = "STEP_CANCELLED"
    STEP_SKIPPED = "STEP_SKIPPED"
    # P3 Events
    ARTIFACT_REVISION_CREATED = "ARTIFACT_REVISION_CREATED"
    ARTIFACT_SET_CANDIDATE_CREATED = "ARTIFACT_SET_CANDIDATE_CREATED"
    ARTIFACT_SET_ACCEPTED = "ARTIFACT_SET_ACCEPTED"
    ARTIFACT_SET_REJECTED = "ARTIFACT_SET_REJECTED"
    FIELD_LOCK_CREATED = "FIELD_LOCK_CREATED"
    FIELD_LOCK_RELEASED = "FIELD_LOCK_RELEASED"
    LOCK_CONFLICT_DETECTED = "LOCK_CONFLICT_DETECTED"
    FEEDBACK_CREATED = "FEEDBACK_CREATED"
    REGENERATION_REQUESTED = "REGENERATION_REQUESTED"
    REGENERATION_STARTED = "REGENERATION_STARTED"
    REGENERATION_COMPLETED = "REGENERATION_COMPLETED"
    REGENERATION_FAILED = "REGENERATION_FAILED"
    CONTEXT_SNAPSHOT_CREATED = "CONTEXT_SNAPSHOT_CREATED"
    DOWNSTREAM_MARKED_STALE = "DOWNSTREAM_MARKED_STALE"
    RERUN_REQUIRED = "RERUN_REQUIRED"
    RERUN_STARTED = "RERUN_STARTED"
    CONTEXT_STALE_WRITE_REJECTED = "CONTEXT_STALE_WRITE_REJECTED"


class AIRunErrorCode(StrEnum):
    """AI 运行及步骤标准错误码"""

    RUN_NOT_FOUND = "RUN_NOT_FOUND"
    RUN_IDEMPOTENCY_CONFLICT = "RUN_IDEMPOTENCY_CONFLICT"
    RUN_INPUT_SCHEMA_INVALID = "RUN_INPUT_SCHEMA_INVALID"
    RUN_CAPABILITY_NOT_RUNNABLE = "RUN_CAPABILITY_NOT_RUNNABLE"
    RUN_VERSION_NOT_RUNNABLE = "RUN_VERSION_NOT_RUNNABLE"
    RUN_CAPABILITY_NOT_NATIVE = "RUN_CAPABILITY_NOT_NATIVE"
    RUN_RUNTIME_PROFILE_INVALID = "RUN_RUNTIME_PROFILE_INVALID"
    RUN_RUNTIME_DISABLED = "RUN_RUNTIME_DISABLED"
    RUN_PROVIDER_NOT_CONFIGURED = "RUN_PROVIDER_NOT_CONFIGURED"
    RUN_PROVIDER_AUTH_FAILED = "RUN_PROVIDER_AUTH_FAILED"
    RUN_PROVIDER_RATE_LIMITED = "RUN_PROVIDER_RATE_LIMITED"
    RUN_PROVIDER_UNAVAILABLE = "RUN_PROVIDER_UNAVAILABLE"
    RUN_PROVIDER_TIMEOUT = "RUN_PROVIDER_TIMEOUT"
    RUN_PROVIDER_RESPONSE_INVALID = "RUN_PROVIDER_RESPONSE_INVALID"
    RUN_OUTPUT_TOO_LARGE = "RUN_OUTPUT_TOO_LARGE"
    RUN_OUTPUT_SCHEMA_INVALID = "RUN_OUTPUT_SCHEMA_INVALID"
    RUN_VALIDATOR_FAILED = "RUN_VALIDATOR_FAILED"
    RUN_HUMAN_REJECTED = "RUN_HUMAN_REJECTED"
    RUN_HUMAN_DECISION_CONFLICT = "RUN_HUMAN_DECISION_CONFLICT"
    RUN_STEP_NOT_RETRYABLE = "RUN_STEP_NOT_RETRYABLE"
    RUN_RETRY_EXHAUSTED = "RUN_RETRY_EXHAUSTED"
    RUN_ALREADY_TERMINAL = "RUN_ALREADY_TERMINAL"
    RUN_CANCEL_CONFLICT = "RUN_CANCEL_CONFLICT"
    RUN_WORKER_CLAIM_EXPIRED = "RUN_WORKER_CLAIM_EXPIRED"
    RUN_WORKER_CLAIM_LOST = "RUN_WORKER_CLAIM_LOST"
    RUN_PACKAGE_INTEGRITY_ERROR = "RUN_PACKAGE_INTEGRITY_ERROR"
    RUN_BUDGET_EXCEEDED = "RUN_BUDGET_EXCEEDED"

    # P3 Error Codes
    REVISION_MODEL_UNAVAILABLE = "REVISION_MODEL_UNAVAILABLE"
    ARTIFACT_NOT_FOUND = "ARTIFACT_NOT_FOUND"
    ARTIFACT_REVISION_NOT_FOUND = "ARTIFACT_REVISION_NOT_FOUND"
    REVISION_SET_NOT_FOUND = "REVISION_SET_NOT_FOUND"
    REVISION_SET_INCOMPLETE = "REVISION_SET_INCOMPLETE"
    REVISION_SET_INVALID = "REVISION_SET_INVALID"
    REVISION_SET_NOT_CANDIDATE = "REVISION_SET_NOT_CANDIDATE"
    REVISION_SET_ALREADY_DECIDED = "REVISION_SET_ALREADY_DECIDED"
    REVISION_BASE_CHANGED = "REVISION_BASE_CHANGED"
    REVISION_ACCEPT_CONFLICT = "REVISION_ACCEPT_CONFLICT"
    REVISION_EDIT_CONFLICT = "REVISION_EDIT_CONFLICT"
    REVISION_RUN_READ_ONLY = "REVISION_RUN_READ_ONLY"
    REVISION_CONTENT_TOO_LARGE = "REVISION_CONTENT_TOO_LARGE"
    REVISION_SCHEMA_INVALID = "REVISION_SCHEMA_INVALID"
    REVISION_COLLECTION_INVALID = "REVISION_COLLECTION_INVALID"
    LOCK_POINTER_INVALID = "LOCK_POINTER_INVALID"
    LOCK_OVERLAP = "LOCK_OVERLAP"
    LOCK_NOT_CURRENT = "LOCK_NOT_CURRENT"
    LOCK_ALREADY_RELEASED = "LOCK_ALREADY_RELEASED"
    LOCK_CONFLICT = "LOCK_CONFLICT"
    FEEDBACK_TARGET_INVALID = "FEEDBACK_TARGET_INVALID"
    FEEDBACK_CONTENT_TOO_LARGE = "FEEDBACK_CONTENT_TOO_LARGE"
    REGENERATION_NOT_SUPPORTED = "REGENERATION_NOT_SUPPORTED"
    REGENERATION_TARGET_INVALID = "REGENERATION_TARGET_INVALID"
    REGENERATION_IDEMPOTENCY_CONFLICT = "REGENERATION_IDEMPOTENCY_CONFLICT"
    REGENERATION_BASE_CHANGED = "REGENERATION_BASE_CHANGED"
    REGENERATION_RESPONSE_INCOMPLETE = "REGENERATION_RESPONSE_INCOMPLETE"
    REGENERATION_OUTPUT_INVALID = "REGENERATION_OUTPUT_INVALID"
    REGENERATION_BLOCKED_BY_LOCK = "REGENERATION_BLOCKED_BY_LOCK"
    CONTEXT_UPSTREAM_NOT_READY = "CONTEXT_UPSTREAM_NOT_READY"
    CONTEXT_SOURCE_NOT_ACCEPTED = "CONTEXT_SOURCE_NOT_ACCEPTED"
    CONTEXT_SOURCE_STALE = "CONTEXT_SOURCE_STALE"
    CONTEXT_SOURCE_INVALID = "CONTEXT_SOURCE_INVALID"
    CONTEXT_FINGERPRINT_MISMATCH = "CONTEXT_FINGERPRINT_MISMATCH"
    CONTEXT_STALE_WRITE_REJECTED = "CONTEXT_STALE_WRITE_REJECTED"
    DEPENDENCY_STALE = "DEPENDENCY_STALE"
    RERUN_NOT_REQUIRED = "RERUN_NOT_REQUIRED"
    EXTERNAL_WORKER_RETIRED = "EXTERNAL_WORKER_RETIRED"
